# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affair_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('project_price', models.DecimalField(decimal_places=2, max_digits=13, null=True, verbose_name='Price of the project')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('trigramme', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_produit', models.CharField(max_length=70, null=True)),
                ('price_std', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Standard price')),
                ('ax_cost', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Cost in AX')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductProject',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend_affaire.Product')),
                ('cost_project', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Project cost')),
                ('price_quotation', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Price quotation')),
            ],
            bases=('backend_affaire.product',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend_affaire.Person')),
                ('region_allocated', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('backend_affaire.person',),
        ),
        migrations.CreateModel(
            name='CompositionNetans',
            fields=[
                ('productproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend_affaire.ProductProject')),
                ('nb_mod_rs422', models.PositiveSmallIntegerField(null=True)),
                ('nb_mod_synchro', models.PositiveSmallIntegerField(null=True)),
                ('nb_mod_ntds', models.PositiveSmallIntegerField(null=True)),
            ],
            bases=('backend_affaire.productproject',),
        ),
        migrations.AddField(
            model_name='productproject',
            name='bid_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_affaire.Bid'),
        ),
    ]
